name: mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  google_fonts: ^4.0.3
  shared_preferences: ^2.1.0
  image_picker: ^0.8.8+7 # Added image_picker dependency
  permission_handler: ^10.2.0 # Added permission_handler for runtime permissions
  http: ^1.0.0 # Added for API communication
  provider: ^6.1.2 # Added for state management (optional)
  razorpay_flutter: ^1.3.5 # Added Razorpay for payment integration
  geolocator: ^9.0.2
  flutter_image_compress: ^2.3.0
  easy_localization: ^3.0.7
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  pdf: ^3.6.0 # Added for PDF generation
  path_provider: ^2.0.10 # Added for file storage location
  open_file: ^3.2.1 # Added for opening files after download
  socket_io_client: ^3.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translation/
